
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6EPvOrgnTvI9dvzYO477hYHIYYVWt9is',
    authDomain: 'course-budy.firebaseapp.com',
    projectId: 'course-budy',
    storageBucket: 'course-budy.firebasestorage.app',
    messagingSenderId: '998718300829',
    appId: '1:998718300829:web:a997f7b729e110eba0aa74',
    measurementId: 'G-7VEZFCJKLF'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA45wE3kdpzHMdR_8YwouPwvyDYOaiYyM',
    appId: '1:998718300829:android:4cc98261ca64459fa0aa74',
    messagingSenderId: '998718300829',
    projectId: 'course-budy',
    storageBucket: 'course-budy.firebasestorage.app'
  );
}
