// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6EPvOrgnTvI9dvzYO477hYHIYYVWt9is',
    appId: '1:998718300829:web:a997f7b729e110eba0aa74',
    messagingSenderId: '998718300829',
    projectId: 'course-budy',
    authDomain: 'course-budy.firebaseapp.com',
    storageBucket: 'course-budy.firebasestorage.app',
    measurementId: 'G-7VEZFCJKLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA45wE3kdpzHMdR_8YwouPwvyDYOaiYyM',
    appId: '1:998718300829:android:4cc98261ca64459fa0aa74',
    messagingSenderId: '998718300829',
    projectId: 'course-budy',
    storageBucket: 'course-budy.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpldgU6wefSuFImqJiwugtd5dtChFEnjo',
    appId: '1:998718300829:ios:0d4e1bf6529a57c7a0aa74',
    messagingSenderId: '998718300829',
    projectId: 'course-budy',
    storageBucket: 'course-budy.firebasestorage.app',
    iosBundleId: 'com.example.coursebuddy',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpldgU6wefSuFImqJiwugtd5dtChFEnjo',
    appId: '1:998718300829:ios:0d4e1bf6529a57c7a0aa74',
    messagingSenderId: '998718300829',
    projectId: 'course-budy',
    storageBucket: 'course-budy.firebasestorage.app',
    iosBundleId: 'com.example.coursebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6EPvOrgnTvI9dvzYO477hYHIYYVWt9is',
    appId: '1:998718300829:web:e3bd2391a4e0a69aa0aa74',
    messagingSenderId: '998718300829',
    projectId: 'course-budy',
    authDomain: 'course-budy.firebaseapp.com',
    storageBucket: 'course-budy.firebasestorage.app',
    measurementId: 'G-MR2WKVG68R',
  );

}