// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpwOQCzIu4upAVN46M3iqNvxSRmD5LgYQ',
    appId: '1:782755032208:web:6e642630ca5d83c1c53c15',
    messagingSenderId: '782755032208',
    projectId: 'course-buddy-5788e',
    authDomain: 'course-buddy-5788e.firebaseapp.com',
    storageBucket: 'course-buddy-5788e.firebasestorage.app',
    measurementId: 'G-YG4WR8Z9GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzi-Xq0hk-9Tj9q0VJKgYfEpaQe4invc',
    appId: '1:782755032208:android:aa18a5d4dec17066c53c15',
    messagingSenderId: '782755032208',
    projectId: 'course-buddy-5788e',
    storageBucket: 'course-buddy-5788e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkzk0u6kLK3EIOT0LyFVTwuC78W8pq4I',
    appId: '1:782755032208:ios:fb1e91ee7e983660c53c15',
    messagingSenderId: '782755032208',
    projectId: 'course-buddy-5788e',
    storageBucket: 'course-buddy-5788e.firebasestorage.app',
    androidClientId: '782755032208-2fsdppjdh3g2iko5cj8a9c8nlch7r4lr.apps.googleusercontent.com',
    iosClientId: '782755032208-6ejij0hoe6m1pbk1duebu45bkji7tu6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUkzk0u6kLK3EIOT0LyFVTwuC78W8pq4I',
    appId: '1:782755032208:ios:fb1e91ee7e983660c53c15',
    messagingSenderId: '782755032208',
    projectId: 'course-buddy-5788e',
    storageBucket: 'course-buddy-5788e.firebasestorage.app',
    androidClientId: '782755032208-2fsdppjdh3g2iko5cj8a9c8nlch7r4lr.apps.googleusercontent.com',
    iosClientId: '782755032208-6ejij0hoe6m1pbk1duebu45bkji7tu6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpwOQCzIu4upAVN46M3iqNvxSRmD5LgYQ',
    appId: '1:782755032208:web:0e71144d74d27d8ac53c15',
    messagingSenderId: '782755032208',
    projectId: 'course-buddy-5788e',
    authDomain: 'course-buddy-5788e.firebaseapp.com',
    storageBucket: 'course-buddy-5788e.firebasestorage.app',
    measurementId: 'G-62GNM5B5NL',
  );
}
